### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by PatrickHeneise** [hummingbird-project/hummingbird-core#35]
In a recent experiment, I forgot to remove the quotation marks in the environment variables:

```
VAR="hello world"
```

which lead to this error when using `HBEnvironment.shared`:

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

It took a while for me to figure out what's wrong. Would be good to either re-phrase that error or load the variable as a string, as it's an easy mistake to make.

**Comment by adam-fowler** [comment]
We never loaded `.env` files up to this point, so I'm not sure how this is related. But anyway a new PR has just been merged which does load `.env` files https://github.com/hummingbird-project/hummingbird/pull/183
