### ISSUE TITLE
Using swift-docc to create documention is failing

### ISSUE THREAD

**Issue by brucemontegani** [hummingbird-project/hummingbird-core#40]
I am trying to use swift-docc to experiment with documenting hummingbird-core. However, I have run into problems.

After building the hummingbird-core package I try and run the docc preview command and I am getting either an error or an illegal hardware instruction.

The error is:  
`Error: Couldn't find the requested node 'doc://com.example.HummingbirdCore/documentation/HummingbirdHTTP2/NIOSSLCertificate' in the documentation context.`

However, sometimes I get this illegal hardware error:
`66571 illegal hardware instruction  xcrun docc preview hummingbirdcore.docc --fallback-display-name     1  .build`

Here are the commands that I am issuing:

```
❯ swift build --target HummingbirdCore -Xswiftc -emit-symbol-graph -Xswiftc -emit-symbol-graph-dir -Xswiftc .build 
Building for debugging...
Build complete! (0.50s)
```
                                                                                                                             
```
❯ xcrun docc preview hummingbirdcore.docc --fallback-display-name HummingbirdCore --fallback-bundle-identifier com.example.HummingbirdCore --fallback-bundle-version 1 --additional-symbol-graph-dir .build

Input: /Users/bruce/Developer/github/brucemontegani/hummingbird-core/hummingbirdcore.docc
Template: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/docc/render
[1]    66571 illegal hardware instruction  xcrun docc preview hummingbirdcore.docc --fallback-display-name     1  .build`
```

Steps:
1. Forked and cloned the hummingbird-core repo.
2. Opened repo in VSCode
3. Added the folder 'hummingbired-core.docc' to the root folder.
4. Changed the swift tools version to 5.7 in the `package,swift` file.
5. `swift build -Xswiftc -emit-symbol-graph -Xswiftc -emit-symbol-graph-dir -Xswiftc .build `
6.  `xcrun docc preview hummingbirdcore.docc --fallback-display-name HummingbirdCore --fallback-bundle-identifier com.example.HummingbirdCore --fallback-bundle-version 1 --additional-symbol-graph-dir .build`

I am just learning `docc` and thought I would try it on this repo.

Software Environment:
MacOS 12.6
Xcode  14.01
Swift 5.7
Visual Studio Code with swift extension

**Comment by adam-fowler** [comment]
Hi Bruce,
I am in the middle of setting up docc for the whole of the hummingbird project. I have split the documentation setup into a separate repo https://github.com/hummingbird-project/hummingbird-docs. You can find the docs [here](https://hummingbird-project.github.io/hummingbird-docs/documentation/hummingbird/).

The script for generating the docs is https://github.com/hummingbird-project/hummingbird-docs/blob/main/scripts/build-docc.sh. I don't use the docc preview command. I use my own [swift-web](https://github.com/adam-fowler/swift-web) app for previewing the content once it is created. 
1) ./script/build-docc.sh
2) swift web docs (in a separate terminal)
3) open http://localhost:8001/hummingbird-docs/documentation/hummingbird

For your issue, if I remember correctly the 5.7 release of docc had some issues. I am using the latest version on the main branch of https://github.com/apple/swift-docc.

**Comment by brucemontegani** [comment]
Adam,

Thank you so much, You have done such a wonderful job with this framework.  As more of a novice using swift I have been looking for a way to contribute. It seems that documentation might be my best way forward.  I will take a look at the new documentation web site and learn from there.

**Comment by adam-fowler** [comment]
If you'd like to contribute to documentation, you should have a look through what docs are available just now and see what you think is missing. You can then contribute to the hummingbird-docs repo. All the documentation is under the [Hummingbird.docc](https://github.com/hummingbird-project/hummingbird-docs/tree/main/Hummingbird.docc) folder. The reference documentation is extracted from the code of course.

**Comment by adam-fowler** [comment]
Closing this as conversation has moved to hummingbird-docs
