### ISSUE TITLE
More informative error message

### ISSUE THREAD

**Issue by pobengtsson** [hummingbird-project/hummingbird-core#41]
As a user of Hummingbird I have experienced this error message:
`HummingbirdCore/HTTPServerHandler.swift:107: Fatal error: Should not get here` 
https://github.com/hummingbird-project/hummingbird-core/blob/fc187b5aeb587de147ba2ae5a2c8a131433dda23/Sources/HummingbirdCore/Server/HTTPServerHandler.swift#L107

 and would really love it if the message could be more helpful in guiding my trouble shooting of my code.
For example, printing information about the context and current values the variables in the scope of the `channelRead` method.

From your perspective, would changing the line into something like:
`assertionFailure("Should not get here! State: \(self.state) part: \(part)")`
make sense?

**Comment by adam-fowler** [comment]
That is an unexpected event. The reason the error message was so brief was it was never expected to be hit. Previously HTTP part processing should ensure this. Given you are hitting it there must be some issue. Feel free to add a PR with your change. Thanks.

**Comment by adam-fowler** [comment]
Have you added any channel handlers using `HBApplication.server.addChannelHandler()` or are you using the hummingbird-compression library?

**Comment by pobengtsson** [comment]
Thanks for your instant reply. I'll put together a PR.

My intention is to use Hummingbird to make a small HTTP2 server to use it as an emulator of an external HTTP2 service in my integration tests. I have based it on the code in the humming-bird examples repo. Here's the code I currently use:
```swift
extension HBApplication {
   public func configure(_ certPath: String,_ privateKey: String, _ subject: PublishSubject<FakeAPNS.ApnsMessage>) throws {
      try server.addHTTP2Upgrade(tlsConfiguration: getTLSConfig(certPath, privateKey))

      router.post("/path/:param") { (request: HBRequest) -> EventLoopFuture<HTTPResponseStatus> in
         print("Logg stuff v\(request.version.major).\(request.version.minor)" +
                             " Param: \(request.parameters["param"] ?? "none")")
         return request.success(.ok)
      }
      middleware.add(HBLogRequestsMiddleware(.trace, includeHeaders: true))
      middleware.add(HBMetricsMiddleware())
   }

   func getTLSConfig(_ certPath: String, _ privateKey: String) throws -> TLSConfiguration {
      do {
         let certificateChain = try NIOSSLCertificate.fromPEMFile(certPath)
         let privateKey = try NIOSSLPrivateKey(file: privateKey, format: .pem)
         var tlsConfig = TLSConfiguration.makeServerConfiguration(certificateChain: certificateChain.map { .certificate($0) },
                                                                  privateKey: .privateKey(privateKey))
         tlsConfig.certificateVerification = .none
         tlsConfig.trustRoots = .file(certPath) // This seems to be the trick to allow a self-signed certificate
         return tlsConfig
      }
   }
}
```

When I added printing of the state and part it the output is:

Client sends 2 different HTTP2 POST requests as part of a test run. 
```
HummingbirdCore/HTTPServerHandler.swift:107: Fatal error: Should not get here!
Part: head(HTTPRequestHead { method: POST, uri: "/path/param-value", version: HTTP/2.0, headers: [("host", "127.0.0.1:2323"), ("transfer-encoding", "chunked"), ("id", "2fd90d72-ec0a-49d9-bc5e-783213d8ec05")] })
State: head(HTTPRequestHead { method: POST, uri: "/path/param-value", version: HTTP/2.0, headers: [("host", "127.0.0.1:2323"), ("transfer-encoding", "chunked"), ("id", "3bfb2b47-373d-45b7-be4c-048198211a3f")] })
```
NOTE: the id in the headers indicate that this is two different POST requests and sent from the same client.

I am a HTTP2 novice, and the problem might very well be due to some mistake that I have made, either in my use of the hummingbird server or in the client, or due to multi-threading as I run the hummingbird server in a separate thread from the test runner.

At this point I would not make any claims that this is a issue with hummingbird, and if you have any hint, its much appreciated!

**Comment by adam-fowler** [comment]
Ok, this may be an issue with the HTTP2 upgrade. How often are you able to replicate this?
Regardless of what the client does it should not be able to crash the server

**Comment by pobengtsson** [comment]
Thanks for your attention here.
The failure happened quite regularly on running my integration tests, so I am quite shure that I can produce som logging from both the client and the server of a run where this happens.
I'll look into this in the next few days.

**Comment by adam-fowler** [comment]
I'm actually surprised you managed to get http2 working. I found an error which meant it kept closing the connection. The fix is on main of hummingbird-core

**Comment by adam-fowler** [comment]
The HTTP2 fix is now in hummingbird-core v1.0.0-rc.2. If you could test it that'd be great

**Comment by pobengtsson** [comment]
Great, many thanks! 

I tested the new release candidate.
Good news - when I send requests manually, single requests in sequence, it does not disconnect after the request, as it did before.
When I run my tests that send multiple requests the unexpected error is still there. I'll post a comment when I have figured out more details on how to reproduce the problem.

**Comment by pobengtsson** [comment]
Actually, now the problem is not showing up when I run my tests. It seems the tests weren't rebuilt properly.
Thanks a bunch! 😄

**Comment by adam-fowler** [comment]
Cool.
