### ISSUE TITLE
maxUploadSize vs maxStreamingBufferSize

### ISSUE THREAD

**Issue by tib** [hummingbird-project/hummingbird-core#46]
I think I might have discovered an issue, not sure how to fix it, but if you guide me to the right direction, I will happily create a PR too. Let me describe the issue first.

I have the following route handler:

```swift 
extension HBApplication {

    func configure(_ args: AppArguments) throws {

        router.post("foo", options: .streamBody) { req async throws -> String in
            guard
                let rawLength = req.headers["Content-Length"].first,
                let length = Int(rawLength),
                let stream = req.body.stream
            else {
                throw HBHTTPError(
                    .badRequest,
                    message: "Missing or invalid body stream."
                )
            }
            var count: Int = 0
            for try await chunk in stream.sequence {
                count += chunk.readableBytes
            }
            return String("\(length) / \(count)")
        }

    }
}
```

The main App is configured like the example below, please note that the `maxUploadSize` property is not set, since I'd like to be able to stream the HTTP body, I don't want to "collect" it. I suppose the `maxStreamingBufferSize` property is used for that purpose, but I might be wrong. (?)

```swift
@main
struct App: ParsableCommand, AppArguments {
    
    @Option(name: .shortAndLong)
    var hostname: String = "127.0.0.1"

    @Option(name: .shortAndLong)
    var port: Int = 8080

    func run() throws {
        let app = HBApplication(
            configuration: .init(
                address: .hostname(self.hostname, port: self.port),
                serverName: "Hummingbird",
                // maxUploadSize: 4 * 1024 * 1024 * 1024,
                maxStreamingBufferSize: 4 * 1024 * 1024 * 1024
            )
        )
        try app.configure(self)
        try app.start()
        app.wait()
    }
}
```

Now if I run the following cURL test, I got a 413 response.

```sh
curl -i -X POST http://localhost:8080/foo \
    -H "content-Length: 464873458" \
    -T ~/test

# HTTP/1.1 413 Payload Too Large
# content-length: 0
# connection: keep-alive
# server: Hummingbird
#
```

The file is around 450MB, so it's way under the 4GB `maxStreamingBufferSize` limit.

I also discovered that [this line](https://github.com/hummingbird-project/hummingbird-core/blob/30851c0774f341db00656c8112c9205ae2f605ce/Sources/HummingbirdCore/Server/HTTPServerHandler.swift#L75) uses the `maxUploadSize` property, when I also set that to 4GB the streaming request works. So I'm not sure if this is an expected behavior, or not.

What do you think about this issue? Thank you. 🙏

**Comment by adam-fowler** [comment]
Ok, my comments are not clear enough. I'll fix that
- `maxUploadSize` is the maximum amount of data a request can include. `maxUploadSize` defaults to 4MB because it is always good practice to have a limit.
- `maxStreamingBufferSize` is the maximum amount of data that can be in-flight before back pressure is applied and we stop reading from the socket. 

So in your example you need to set `maxUploadSize ` to above 450MB.

**Comment by tib** [comment]
Hm... so this means that `Int.max` size is the maximum limit that I can stream through a HB server? Also can I set this on a per-route basis and not globally?

I'd be nice to eliminate this limitation for request handlers with the option `.streamBody`, but I'd like to keep a max of (idk) 4MB for every other route. Can I achieve this somehow?

In Vapor, `maxUploadSize` can be specified per-route, and when you stream a request there's no limitation, since data arrives as a chunk of byte buffers, which is nice.

What do you think about this? 🤔

**Comment by adam-fowler** [comment]
Int.max is 9,223,372,036,854,775,807 (2^63 - 1) that should be enough. 

Regarding max upload limits we could probably add two sizes one for streamed payloads and one for normal payloads. Vapor's limit per request most likely means the route manages the max size instead of the http channel so if the route is slow to process a stream the http channel will stream more than it should. I am guessing to some degree here I find the vapor stream implementation completely opaque.

**Comment by tib** [comment]
AFAIK: They try to read up a fixed amount of data for standard requests, based on the content length / max upload size for regular requests. For streamed requests, they try to read everything regardless of the size. 

I'm not sure how you stream the body data & how decoding works under the hood, I'm going to take a look on that part for sure, but this is closer to the channel / NIO level I suppose.

Anyway, I have to dig a bit deeper how you handle these kind of things in HB. I'm just scratching the surface so yeah, I might going to have more questions like this, but thanks for the clarification & help. 🙏

**Comment by adam-fowler** [comment]
I'm going to add a separate upload limits for streamed and non-streamed routes.
- The limit for non-streamed routes is really a limit on how much memory they can use
- The limit for streamed routes is a limit on how much data can be passed to this route (this is basically the current `maxUploadLimit`).

#48 is a start. It means I can limit the size of buffers being collated

**Comment by adam-fowler** [comment]
Hummingbird PR is https://github.com/hummingbird-project/hummingbird/pull/184

**Comment by tib** [comment]
Looks really good, after the PR is merged, I suppose we can close this issue. Thanks. :)

**Comment by adam-fowler** [comment]
This is in v1.4.0
